### ISSUE TITLE
A few ideas, Player shop

### ISSUE THREAD

**Issue by haojie06** [OtorisanVardo/EconomySignBusiness#1]
Your plugin is very well, it solves the problem that has plagued me for a long time. However only op can use this plugin,  in servers, the trade between Players is also important, can you add some features just like the Chest Shop in old versions. Players can also set a sign closed to the chest, they can put items in the chest to sell them or buy things from others, this items will be stored in the chest.
Thank you for your share.

**Comment by OtorisanVardo** [comment]
Thank you for reviewing.
However, i won't think that i'm going to make a function like it yet.
I didn't think that someone who lives abroad is used this plugin.
At first, this plugin made for one Japanese server developer.

Someday, I maybe make the new plugin like it.
By the way, Do you think i should make this plugin in English?

**Comment by haojie06** [comment]
I think many foreigners will use your plugin just like me（I am Chinese） and it's a good idea to make this plugin in English which can enable more people to use this plugin conveniently. There aren't sophisticated chest/sign shop plugins which can run in the new API, many people are looking forward to it. Thank you for your sharing once anagin. Looking forward to your works.
